import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Providers from "../components/Provider";
import Navbar from "../components/Navbar";
import { Toaster } from "react-hot-toast";
import ModalRender from "../components/ModalRender";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "JPD",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <Providers>
          <Toaster position="top-center" reverseOrder={false} />
          <>

            <div className="sm:h-full w-full">
              <div className="h-[54px] w-full border-b border-[#E0DEF7]">
                <Navbar />
              </div>
              <div className="h-[calc(100%-54px)]  w-full bg-[#F7F7FD]">
                {children}
              </div>
            </div>
          </>
          {/* Render modals */}
          <ModalRender />
        </Providers>
      </body>
    </html>
  );
}
